### ISSUE TITLE
Compatibility with sublime-syntax files?

### ISSUE THREAD

**Issue by hunhejj** [Togusa09/vscode-tmlanguage#13]
Is this plugin supposed to convert the new sublime-syntax files as well? See https://www.sublimetext.com/docs/3/syntax.html
I can't get it to work.

**Comment by Togusa09** [comment]
The sublime syntax files are not supported. The three formats currently supported (tmLanguage, json-tmlLanguage and yaml-tmLanguage) are really the same, they just differ in using plist, json or yaml to store the information.

The primary reason to support conversion between these is because plist files are a nightmare to edit compared to json/yaml, but vscode requires tmLanguage files be plist.

I'll have a look at how much work it is to add extra support, but no promises on this one.

**Comment by hunhejj** [comment]
I just checked it and actually they are quite different, so I think it's too complex to do an automatical conversion. Hence I will close this issue.
